"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mod_1 = require("./mod");
var mod_2 = require("./mod");
var mod_3 = require("./mod");
var mod_4 = require("./mod");
var mod_5 = require("./mod");
var mod_6 = require("./mod");
var mod_7 = require("./mod");
var mod_8 = require("./mod");
console.log();
console.log("1.Sum of even numbers in an array ".concat((0, mod_1.default)()));
console.log();
console.log("2.Is Panindrome ".concat((0, mod_2.CheckPalindrome)("pipp")));
console.log();
console.log("3.UpperCase Result Array [".concat((0, mod_3.ReturnUpperCases)(["HI", "hi", "THIS", "this", "IS", "is", "MAYIHS", "mayihs"]), "]"));
console.log();
console.log("4.Join Array [".concat((0, mod_4.ArrayJoin)(["Hi", "this"], ["is", "shiyam", "k"]), "]"));
console.log();
console.log("5.Unique Numbers [".concat((0, mod_5.UniqueNumbers)([1, 1, 2, 4, 4, 3, 3, 5, 6, 8, 9, 7, 7]), "]"));
console.log();
console.log("6.Min Integer [".concat((0, mod_6.ReturnMin)([-1, 1, 2, 4, 4, 3, 3, 5, 6, 8, 9, 7, 7]), "]"));
console.log();
console.log("7.String Cut ".concat((0, mod_7.StringCut)("Hola Amigos", 5)));
console.log();
console.log("8.To LowerCase ".concat((0, mod_8.ToLowerCase)(["HI, ThIs", "MaYiHs"])));
console.log();
