// <auto-generated />
using API_OnetoMany.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_OnetoMany.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20230525055738_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_OnetoMany.Models.Doctor", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Did"));

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DName");

                    b.HasKey("Did");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("API_OnetoMany.Models.Patient", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"));

                    b.Property<int>("DoctorsDid")
                        .HasColumnType("int")
                        .HasColumnName("DoctorsDId");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PName");

                    b.HasKey("Pid");

                    b.HasIndex(new[] { "DoctorsDid" }, "IX_Patients_DoctorsDId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("API_OnetoMany.Models.Patient", b =>
                {
                    b.HasOne("API_OnetoMany.Models.Doctor", "DoctorsD")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorsDid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorsD");
                });

            modelBuilder.Entity("API_OnetoMany.Models.Doctor", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
